export const API_BASE = 'http://localhost:3000';

export const BOMB_OVERLAY_ID = 'bombOverlay';

export enum Pages {
  Home = '/',
  Game = '/game',
  Profile = '/profile',
  Auth = '/auth',
  Rules = '/rules',
  Leaders = '/leaders',
  Cash = '/cash',
  Comic = '/comic',
  ForgotPassword = '/forgot-password',
  ResetPassword = '/reset-password',
  AskToConfirmEmail = '/ask-to-confirm-email',
  ConfirmEmail = '/confirm-email',
}

export enum SOUND_TYPE {
  BUM = 'bum',
  COINS = 'coins',
  GAME = 'game',
  THROW_BOMB = 'throwBomb',
  LOSE = 'lose',
  VICTORY = 'victory',
}

export enum ANIMATIONS_TYPE {
  GRANDMA = 'GRANDMA',
  LOSER = 'LOSER',
  PRIZE = 'PRIZE',
}

export const ANIMATIONS = {
  [ANIMATIONS_TYPE.GRANDMA]:
    'https://lottie.host/ede8a463-190f-48c8-8888-8c163fe393b0/8DFN7sP0za.json',
  [ANIMATIONS_TYPE.LOSER]:
    'https://lottie.host/1d78b59a-d4ac-4439-8670-de3656a6e2a5/efm6X6xQf7.json',
  [ANIMATIONS_TYPE.PRIZE]:
    'https://lottie.host/d54aa7cf-dc80-465c-8175-871edb269141/zdqnzQUoyp.json',
};

export const userNames = [
  'Alice',
  'Bob',
  'Charlie',
  'David',
  'Eve',
  'Frank',
  'Grace',
  'Hank',
  'Ivy',
  'Jack',
  'Kathy',
  'Leo',
  'Mona',
  'Nina',
  'Oscar',
  'Pete',
  'Quinn',
  'Rachel',
  'Steve',
  'Tina',
  'NNikola',
  'Jora77N',
  'ГошаME',
  'Jora77C',
  'УБTraf',
  'Race8',
  '7GAME',
  'НикНетk',
  'PiРусніp',
  'Jora77Q',
  'RaceRJK',
  'НикНетY',
  'PiРусні0',
  'NameX1',
  'NameX2',
  'NameX3',
  'NameX4',
  'NameX5',
  'Lara',
  'Mike',
  'Nancy',
  'Olga',
  'Paul',
  'Queen',
  'Rob',
  'Sam',
  'Tom',
  'Uma',
  'Vera',
  'Walt',
  'Xena',
  'Yana',
  'Zack',
  'Anna',
  'Boris',
  'Carl',
  'Diana',
  'Elon',
  'Fred',
  'Gina',
  'Harry',
  'Irene',
  'Jackie',
];

export const userAvatars = [
  '/imgs/users/u-01.png',
  '/imgs/users/u-01.svg',
  '/imgs/users/u-02.png',
  '/imgs/users/u-02.svg',
  '/imgs/users/u-03.png',
  '/imgs/users/u-03.svg',
  '/imgs/users/u-04.png',
  '/imgs/users/u-04.svg',
  '/imgs/users/u-05.png',
  '/imgs/users/u-05.svg',
  '/imgs/users/u-06.png',
  '/imgs/users/u-06.svg',
  '/imgs/users/u-07.png',
  '/imgs/users/u-07.svg',
  '/imgs/users/u-08.png',
  '/imgs/users/u-08.svg',
  '/imgs/users/u-09.png',
  '/imgs/users/u-09.svg',
  '/imgs/users/u-10.png',
  '/imgs/users/u-11.png',
  '/imgs/users/u-12.png',
  '/imgs/users/u-13.png',
  '/imgs/users/u-14.png',
  '/imgs/users/u-15.png',
  '/imgs/users/u-16.png',
  '/imgs/users/u-17.png',
  '/imgs/users/u-18.png',
  '/imgs/users/u-19.png',
  '/imgs/users/u-20.png',
  '/imgs/users/u-001.svg',
];
